#### Connecting to clever cloud mysql

In [28]:
#!pip3 install mysql-connector-python

In [42]:
import mysql.connector 
from mysql.connector import Error
import pandas as pd

In [43]:
connection = mysql.connector.connect(
  host="bybz54wnxrpm7fu13bib-mysql.services.clever-cloud.com", # replace username, hostname, password and database name appropriately
  user="u5bzf3s3fpxkrg5t",
  password="X6CUkrBLPGlozcFG7N9u",
  database="bybz54wnxrpm7fu13bib"
)

cursor1 = connection.cursor()

In [46]:
df = pd.read_csv('titanic_train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df1=df.iloc[:,0:5]
df2.head()

In [60]:
df2=df.iloc[:,[0,6,7,8]]
df2.head()

   PassengerId  SibSp  Parch            Ticket
0            1      1      0         A/5 21171
1            2      1      0          PC 17599
2            3      0      0  STON/O2. 3101282
3            4      1      0            113803
4            5      0      0            373450

In [ ]:
df3=df.iloc[:,[0,9,10,11]]
df2.head()

###### Setp_1 : Creating a Table in DB name Table_1

In [52]:
cursor1.execute("CREATE TABLE Titanic_01 (PassengerId INT,Survived INT,Pclass INT,Name VARCHAR(255), Gender VARCHAR(255))")

In [61]:
cursor1.execute("CREATE TABLE Titanic_02 (PassengerId INT,SibSp INT,Parch INT,Ticket VARCHAR(255))")

###### Setp2 :Inserting data to the table Table_1

In [53]:
for row in df1.iterrows():
    #print( row[1].values)
    sql="INSERT INTO Titanic_01 (PassengerId,Survived,Pclass,Name,Gender) VALUES (%s ,%s,%s ,%s,%s)"  #insert a single tuple
    val=tuple(row[1].values)
    cursor1.execute(sql,val)

In [62]:
for row in df2.iterrows():
    #print( row[1].values)
    sql="INSERT INTO Titanic_02 (PassengerId,SibSp,Parch,Ticket) VALUES (%s ,%s,%s ,%s)"  #insert a single tuple
    val=tuple(row[1].values)
    cursor1.execute(sql,val)

###### LOADING THE DATA FROM THE TABLE

In [57]:
cursor1.execute('''SELECT * 
                 FROM Titanic_01
                 
                 ''')
result2=cursor1.fetchall()   #fetch all the tuple

for i in result2:
    print(i)

(1, 0, 3, 'Braund, Mr. Owen Harris', 'male')
(2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female')
(3, 1, 3, 'Heikkinen, Miss. Laina', 'female')
(4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female')
(5, 0, 3, 'Allen, Mr. William Henry', 'male')
(6, 0, 3, 'Moran, Mr. James', 'male')
(7, 0, 1, 'McCarthy, Mr. Timothy J', 'male')
(8, 0, 3, 'Palsson, Master. Gosta Leonard', 'male')
(9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'female')
(10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female')
(11, 1, 3, 'Sandstrom, Miss. Marguerite Rut', 'female')
(12, 1, 1, 'Bonnell, Miss. Elizabeth', 'female')
(13, 0, 3, 'Saundercock, Mr. William Henry', 'male')
(14, 0, 3, 'Andersson, Mr. Anders Johan', 'male')
(15, 0, 3, 'Vestrom, Miss. Hulda Amanda Adolfina', 'female')
(16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female')
(17, 0, 3, 'Rice, Master. Eugene', 'male')
(18, 1, 2, 'Williams, Mr. Charles Eugene', 'male')
(19, 0, 3, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'female')
(20, 1, 3, 'Masselmani, Mrs. Fatima', 'female')
(21, 0, 2, 'Fynney, Mr. Joseph J', 'male')
(22, 1, 2, 'Beesley, Mr. Lawrence', 'male')
(23, 1, 3, 'McGowan, Miss. Anna "Annie"', 'female')
(24, 1, 1, 'Sloper, Mr. William Thompson', 'male')
(25, 0, 3, 'Palsson, Miss. Torborg Danira', 'female')
(26, 1, 3, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'female')
(27, 0, 3, 'Emir, Mr. Farred Chehab', 'male')
(28, 0, 1, 'Fortune, Mr. Charles Alexander', 'male')
(29, 1, 3, 'O\'Dwyer, Miss. Ellen "Nellie"', 'female')
(30, 0, 3, 'Todoroff, Mr. Lalio', 'male')
(31, 0, 1, 'Uruchurtu, Don. Manuel E', 'male')
(32, 1, 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'female')
(33, 1, 3, 'Glynn, Miss. Mary Agatha', 'female')
(34, 0, 2, 'Wheadon, Mr. Edward H', 'male')
(35, 0, 1, 'Meyer, Mr. Edgar Joseph', 'male')
(36, 0, 1, 'Holverson, Mr. Alexander Oskar', 'male')
(37, 1, 3, 'Mamee, Mr. Hanna', 'male')
(38, 0, 3, 'Cann, Mr. Ernest Charles', 'male')
(39, 0, 3, 'Vander Planke, Miss. Augusta Maria', 'female')
(40, 1, 3, 'Nicola-Yarred, Miss. Jamila', 'female')
(41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'female')
(42, 0, 2, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'female')
(43, 0, 3, 'Kraeff, Mr. Theodor', 'male')
(44, 1, 2, 'Laroche, Miss. Simonne Marie Anne Andree', 'female')
(45, 1, 3, 'Devaney, Miss. Margaret Delia', 'female')
(46, 0, 3, 'Rogers, Mr. William John', 'male')
(47, 0, 3, 'Lennon, Mr. Denis', 'male')
(48, 1, 3, "O'Driscoll, Miss. Bridget", 'female')
(49, 0, 3, 'Samaan, Mr. Youssef', 'male')
(50, 0, 3, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'female')
(51, 0, 3, 'Panula, Master. Juha Niilo', 'male')
(52, 0, 3, 'Nosworthy, Mr. Richard Cater', 'male')
(53, 1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female')
(54, 1, 2, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'female')
(55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male')
(56, 1, 1, 'Woolner, Mr. Hugh', 'male')
(57, 1, 2, 'Rugg, Miss. Emily', 'female')
(58, 0, 3, 'Novel, Mr. Mansouer', 'male')
(59, 1, 2, 'West, Miss. Constance Mirium', 'female')
(60, 0, 3, 'Goodwin, Master. William Frederick', 'male')
(61, 0, 3, 'Sirayanian, Mr. Orsen', 'male')
(62, 1, 1, 'Icard, Miss. Amelie', 'female')
(63, 0, 1, 'Harris, Mr. Henry Birkhardt', 'male')
(64, 0, 3, 'Skoog, Master. Harald', 'male')
(65, 0, 1, 'Stewart, Mr. Albert A', 'male')
(66, 1, 3, 'Moubarek, Master. Gerios', 'male')
(67, 1, 2, 'Nye, Mrs. (Elizabeth Ramell)', 'female')
(68, 0, 3, 'Crease, Mr. Ernest James', 'male')
(69, 1, 3, 'Andersson, Miss. Erna Alexandra', 'female')
(70, 0, 3, 'Kink, Mr. Vincenz', 'male')
(71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 'male')
(72, 0, 3, 'Goodwin, Miss. Lillian Amy', 'female')
(73, 0, 2, 'Hood, Mr. Ambrose Jr', 'male')
(74, 0, 3, 'Chronopoulos, Mr. Apostolos', 'male')
(75, 1, 3, 'Bing, Mr. Lee', 'male')
(76, 0, 3, 'Moen, Mr. Sigurd Hansen', 'male')
(77, 0, 3, 'Staneff, Mr. Ivan', 'male')
(78, 0, 3, 'Moutal, Mr. Rahamin Haim', 'male')
(79, 1, 2, 'Caldwell, Master. Alden Gates', 'male')
(80, 1, 3, 'Dowdell, Miss. Elizabeth', 'female')
(81, 0, 3, 'Waelens, Mr. Achille', 'male')
(82, 1, 3, 'Sheerlinck, Mr. Jan Baptist', 'male')
(83, 1, 3, 'McDermott, Miss. Brigdet Delia', 'female')
(84, 0, 1, 'Carrau, Mr. Francisco M', 'male')
(85, 1, 2, 'Ilett, Miss. Bertha', 'female')
(86, 1, 3, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'female')
(87, 0, 3, 'Ford, Mr. William Neal', 'male')
(88, 0, 3, 'Slocovski, Mr. Selman Francis', 'male')
(89, 1, 1, 'Fortune, Miss. Mabel Helen', 'female')
(90, 0, 3, 'Celotti, Mr. Francesco', 'male')
(91, 0, 3, 'Christmann, Mr. Emil', 'male')
(92, 0, 3, 'Andreasson, Mr. Paul Edvin', 'male')
(93, 0, 1, 'Chaffee, Mr. Herbert Fuller', 'male')
(94, 0, 3, 'Dean, Mr. Bertram Frank', 'male')
(95, 0, 3, 'Coxon, Mr. Daniel', 'male')
(96, 0, 3, 'Shorney, Mr. Charles Joseph', 'male')
(97, 0, 1, 'Goldschmidt, Mr. George B', 'male')
(98, 1, 1, 'Greenfield, Mr. William Bertram', 'male')
(99, 1, 2, 'Doling, Mrs. John T (Ada Julia Bone)', 'female')
(100, 0, 2, 'Kantor, Mr. Sinai', 'male')
(101, 0, 3, 'Petranec, Miss. Matilda', 'female')
(102, 0, 3, 'Petroff, Mr. Pastcho ("Pentcho")', 'male')
(103, 0, 1, 'White, Mr. Richard Frasar', 'male')
(104, 0, 3, 'Johansson, Mr. Gustaf Joel', 'male')
(105, 0, 3, 'Gustafsson, Mr. Anders Vilhelm', 'male')
(106, 0, 3, 'Mionoff, Mr. Stoytcho', 'male')
(107, 1, 3, 'Salkjelsvik, Miss. Anna Kristine', 'female')
(108, 1, 3, 'Moss, Mr. Albert Johan', 'male')
(109, 0, 3, 'Rekic, Mr. Tido', 'male')
(110, 1, 3, 'Moran, Miss. Bertha', 'female')
(111, 0, 1, 'Porter, Mr. Walter Chamberlain', 'male')
(112, 0, 3, 'Zabour, Miss. Hileni', 'female')
(113, 0, 3, 'Barton, Mr. David John', 'male')
(114, 0, 3, 'Jussila, Miss. Katriina', 'female')
(115, 0, 3, 'Attalah, Miss. Malake', 'female')
(116, 0, 3, 'Pekoniemi, Mr. Edvard', 'male')
(117, 0, 3, 'Connors, Mr. Patrick', 'male')
(118, 0, 2, 'Turpin, Mr. William John Robert', 'male')
(119, 0, 1, 'Baxter, Mr. Quigg Edmond', 'male')
(120, 0, 3, 'Andersson, Miss. Ellis Anna Maria', 'female')
(121, 0, 2, 'Hickman, Mr. Stanley George', 'male')
(122, 0, 3, 'Moore, Mr. Leonard Charles', 'male')
(123, 0, 2, 'Nasser, Mr. Nicholas', 'male')
(124, 1, 2, 'Webber, Miss. Susan', 'female')
(125, 0, 1, 'White, Mr. Percival Wayland', 'male')
(126, 1, 3, 'Nicola-Yarred, Master. Elias', 'male')
(127, 0, 3, 'McMahon, Mr. Martin', 'male')
(128, 1, 3, 'Madsen, Mr. Fridtjof Arne', 'male')
(129, 1, 3, 'Peter, Miss. Anna', 'female')
(130, 0, 3, 'Ekstrom, Mr. Johan', 'male')
(131, 0, 3, 'Drazenoic, Mr. Jozef', 'male')
(132, 0, 3, 'Coelho, Mr. Domingos Fernandeo', 'male')
(133, 0, 3, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'female')
(134, 1, 2, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'female')
(135, 0, 2, 'Sobey, Mr. Samuel James Hayden', 'male')
(136, 0, 2, 'Richard, Mr. Emile', 'male')
(137, 1, 1, 'Newsom, Miss. Helen Monypeny', 'female')
(138, 0, 1, 'Futrelle, Mr. Jacques Heath', 'male')
(139, 0, 3, 'Osen, Mr. Olaf Elon', 'male')
(140, 0, 1, 'Giglio, Mr. Victor', 'male')
(141, 0, 3, 'Boulos, Mrs. Joseph (Sultana)', 'female')
(142, 1, 3, 'Nysten, Miss. Anna Sofia', 'female')
(143, 1, 3, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'female')
(144, 0, 3, 'Burke, Mr. Jeremiah', 'male')
(145, 0, 2, 'Andrew, Mr. Edgardo Samuel', 'male')
(146, 0, 2, 'Nicholls, Mr. Joseph Charles', 'male')
(147, 1, 3, 'Andersson, Mr. August Edvard ("Wennerstrom")', 'male')
(148, 0, 3, 'Ford, Miss. Robina Maggie "Ruby"', 'female')
(149, 0, 2, 'Navratil, Mr. Michel ("Louis M Hoffman")', 'male')
(150, 0, 2, 'Byles, Rev. Thomas Roussel Davids', 'male')
(151, 0, 2, 'Bateman, Rev. Robert James', 'male')
(152, 1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female')
(153, 0, 3, 'Meo, Mr. Alfonzo', 'male')
(154, 0, 3, 'van Billiard, Mr. Austin Blyler', 'male')
(155, 0, 3, 'Olsen, Mr. Ole Martin', 'male')
(156, 0, 1, 'Williams, Mr. Charles Duane', 'male')
(157, 1, 3, 'Gilnagh, Miss. Katherine "Katie"', 'female')
(158, 0, 3, 'Corn, Mr. Harry', 'male')
(159, 0, 3, 'Smiljanic, Mr. Mile', 'male')
(160, 0, 3, 'Sage, Master. Thomas Henry', 'male')
(161, 0, 3, 'Cribb, Mr. John Hatfield', 'male')
(162, 1, 2, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 'female')
(163, 0, 3, 'Bengtsson, Mr. John Viktor', 'male')
(164, 0, 3, 'Calic, Mr. Jovo', 'male')
(165, 0, 3, 'Panula, Master. Eino Viljami', 'male')
(166, 1, 3, 'Goldsmith, Master. Frank John William "Frankie"', 'male')
(167, 1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female')
(168, 0, 3, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 'female')
(169, 0, 1, 'Baumann, Mr. John D', 'male')
(170, 0, 3, 'Ling, Mr. Lee', 'male')
(171, 0, 1, 'Van der hoef, Mr. Wyckoff', 'male')
(172, 0, 3, 'Rice, Master. Arthur', 'male')
(173, 1, 3, 'Johnson, Miss. Eleanor Ileen', 'female')
(174, 0, 3, 'Sivola, Mr. Antti Wilhelm', 'male')
(175, 0, 1, 'Smith, Mr. James Clinch', 'male')
(176, 0, 3, 'Klasen, Mr. Klas Albin', 'male')
(177, 0, 3, 'Lefebre, Master. Henry Forbes', 'male')
(178, 0, 1, 'Isham, Miss. Ann Elizabeth', 'female')
(179, 0, 2, 'Hale, Mr. Reginald', 'male')
(180, 0, 3, 'Leonard, Mr. Lionel', 'male')
(181, 0, 3, 'Sage, Miss. Constance Gladys', 'female')
(182, 0, 2, 'Pernot, Mr. Rene', 'male')
(183, 0, 3, 'Asplund, Master. Clarence Gustaf Hugo', 'male')
(184, 1, 2, 'Becker, Master. Richard F', 'male')
(185, 1, 3, 'Kink-Heilmann, Miss. Luise Gretchen', 'female')
(186, 0, 1, 'Rood, Mr. Hugh Roscoe', 'male')
(187, 1, 3, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 'female')
(188, 1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male')
(189, 0, 3, 'Bourke, Mr. John', 'male')
(190, 0, 3, 'Turcin, Mr. Stjepan', 'male')
(191, 1, 2, 'Pinsky, Mrs. (Rosa)', 'female')
(192, 0, 2, 'Carbines, Mr. William', 'male')
(193, 1, 3, 'Andersen-Jensen, Miss. Carla Christine Nielsine', 'female')
(194, 1, 2, 'Navratil, Master. Michel M', 'male')
(195, 1, 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female')
(196, 1, 1, 'Lurette, Miss. Elise', 'female')
(197, 0, 3, 'Mernagh, Mr. Robert', 'male')
(198, 0, 3, 'Olsen, Mr. Karl Siegwart Andreas', 'male')
(199, 1, 3, 'Madigan, Miss. Margaret "Maggie"', 'female')
(200, 0, 2, 'Yrois, Miss. Henriette ("Mrs Harbeck")', 'female')
(201, 0, 3, 'Vande Walle, Mr. Nestor Cyriel', 'male')
(202, 0, 3, 'Sage, Mr. Frederick', 'male')
(203, 0, 3, 'Johanson, Mr. Jakob Alfred', 'male')
(204, 0, 3, 'Youseff, Mr. Gerious', 'male')
(205, 1, 3, 'Cohen, Mr. Gurshon "Gus"', 'male')
(206, 0, 3, 'Strom, Miss. Telma Matilda', 'female')
(207, 0, 3, 'Backstrom, Mr. Karl Alfred', 'male')
(208, 1, 3, 'Albimona, Mr. Nassef Cassem', 'male')
(209, 1, 3, 'Carr, Miss. Helen "Ellen"', 'female')
(210, 1, 1, 'Blank, Mr. Henry', 'male')
(211, 0, 3, 'Ali, Mr. Ahmed', 'male')
(212, 1, 2, 'Cameron, Miss. Clear Annie', 'female')
(213, 0, 3, 'Perkin, Mr. John Henry', 'male')
(214, 0, 2, 'Givard, Mr. Hans Kristensen', 'male')
(215, 0, 3, 'Kiernan, Mr. Philip', 'male')
(216, 1, 1, 'Newell, Miss. Madeleine', 'female')
(217, 1, 3, 'Honkanen, Miss. Eliina', 'female')
(218, 0, 2, 'Jacobsohn, Mr. Sidney Samuel', 'male')
(219, 1, 1, 'Bazzani, Miss. Albina', 'female')
(220, 0, 2, 'Harris, Mr. Walter', 'male')
(221, 1, 3, 'Sunderland, Mr. Victor Francis', 'male')
(222, 0, 2, 'Bracken, Mr. James H', 'male')
(223, 0, 3, 'Green, Mr. George Henry', 'male')
(224, 0, 3, 'Nenkoff, Mr. Christo', 'male')
(225, 1, 1, 'Hoyt, Mr. Frederick Maxfield', 'male')
(226, 0, 3, 'Berglund, Mr. Karl Ivar Sven', 'male')
(227, 1, 2, 'Mellors, Mr. William John', 'male')
(228, 0, 3, 'Lovell, Mr. John Hall ("Henry")', 'male')
(229, 0, 2, 'Fahlstrom, Mr. Arne Jonas', 'male')
(230, 0, 3, 'Lefebre, Miss. Mathilde', 'female')
(231, 1, 1, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 'female')
(232, 0, 3, 'Larsson, Mr. Bengt Edvin', 'male')
(233, 0, 2, 'Sjostedt, Mr. Ernst Adolf', 'male')
(234, 1, 3, 'Asplund, Miss. Lillian Gertrud', 'female')
(235, 0, 2, 'Leyson, Mr. Robert William Norman', 'male')
(236, 0, 3, 'Harknett, Miss. Alice Phoebe', 'female')
(237, 0, 2, 'Hold, Mr. Stephen', 'male')
(238, 1, 2, 'Collyer, Miss. Marjorie "Lottie"', 'female')
(239, 0, 2, 'Pengelly, Mr. Frederick William', 'male')
(240, 0, 2, 'Hunt, Mr. George Henry', 'male')
(241, 0, 3, 'Zabour, Miss. Thamine', 'female')
(242, 1, 3, 'Murphy, Miss. Katherine "Kate"', 'female')
(243, 0, 2, 'Coleridge, Mr. Reginald Charles', 'male')
(244, 0, 3, 'Maenpaa, Mr. Matti Alexanteri', 'male')
(245, 0, 3, 'Attalah, Mr. Sleiman', 'male')
(246, 0, 1, 'Minahan, Dr. William Edward', 'male')
(247, 0, 3, 'Lindahl, Miss. Agda Thorilda Viktoria', 'female')
(248, 1, 2, 'Hamalainen, Mrs. William (Anna)', 'female')
(249, 1, 1, 'Beckwith, Mr. Richard Leonard', 'male')
(250, 0, 2, 'Carter, Rev. Ernest Courtenay', 'male')
(251, 0, 3, 'Reed, Mr. James George', 'male')
(252, 0, 3, 'Strom, Mrs. Wilhelm (Elna Matilda Persson)', 'female')
(253, 0, 1, 'Stead, Mr. William Thomas', 'male')
(254, 0, 3, 'Lobb, Mr. William Arthur', 'male')
(255, 0, 3, 'Rosblom, Mrs. Viktor (Helena Wilhelmina)', 'female')
(256, 1, 3, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 'female')
(257, 1, 1, 'Thorne, Mrs. Gertrude Maybelle', 'female')
(258, 1, 1, 'Cherry, Miss. Gladys', 'female')
(259, 1, 1, 'Ward, Miss. Anna', 'female')
(260, 1, 2, 'Parrish, Mrs. (Lutie Davis)', 'female')
(261, 0, 3, 'Smith, Mr. Thomas', 'male')
(262, 1, 3, 'Asplund, Master. Edvin Rojj Felix', 'male')
(263, 0, 1, 'Taussig, Mr. Emil', 'male')
(264, 0, 1, 'Harrison, Mr. William', 'male')
(265, 0, 3, 'Henry, Miss. Delia', 'female')
(266, 0, 2, 'Reeves, Mr. David', 'male')
(267, 0, 3, 'Panula, Mr. Ernesti Arvid', 'male')
(268, 1, 3, 'Persson, Mr. Ernst Ulrik', 'male')
(269, 1, 1, 'Graham, Mrs. William Thompson (Edith Junkins)', 'female')
(270, 1, 1, 'Bissette, Miss. Amelia', 'female')
(271, 0, 1, 'Cairns, Mr. Alexander', 'male')
(272, 1, 3, 'Tornquist, Mr. William Henry', 'male')
(273, 1, 2, 'Mellinger, Mrs. (Elizabeth Anne Maidment)', 'female')
(274, 0, 1, 'Natsch, Mr. Charles H', 'male')
(275, 1, 3, 'Healy, Miss. Hanora "Nora"', 'female')
(276, 1, 1, 'Andrews, Miss. Kornelia Theodosia', 'female')
(277, 0, 3, 'Lindblom, Miss. Augusta Charlotta', 'female')
(278, 0, 2, 'Parkes, Mr. Francis "Frank"', 'male')
(279, 0, 3, 'Rice, Master. Eric', 'male')
(280, 1, 3, 'Abbott, Mrs. Stanton (Rosa Hunt)', 'female')
(281, 0, 3, 'Duane, Mr. Frank', 'male')
(282, 0, 3, 'Olsson, Mr. Nils Johan Goransson', 'male')
(283, 0, 3, 'de Pelsmaeker, Mr. Alfons', 'male')
(284, 1, 3, 'Dorking, Mr. Edward Arthur', 'male')
(285, 0, 1, 'Smith, Mr. Richard William', 'male')
(286, 0, 3, 'Stankovic, Mr. Ivan', 'male')
(287, 1, 3, 'de Mulder, Mr. Theodore', 'male')
(288, 0, 3, 'Naidenoff, Mr. Penko', 'male')
(289, 1, 2, 'Hosono, Mr. Masabumi', 'male')
(290, 1, 3, 'Connolly, Miss. Kate', 'female')
(291, 1, 1, 'Barber, Miss. Ellen "Nellie"', 'female')
(292, 1, 1, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female')
(293, 0, 2, 'Levy, Mr. Rene Jacques', 'male')
(294, 0, 3, 'Haas, Miss. Aloisia', 'female')
(295, 0, 3, 'Mineff, Mr. Ivan', 'male')
(296, 0, 1, 'Lewy, Mr. Ervin G', 'male')
(297, 0, 3, 'Hanna, Mr. Mansour', 'male')
(298, 0, 1, 'Allison, Miss. Helen Loraine', 'female')
(299, 1, 1, 'Saalfeld, Mr. Adolphe', 'male')
(300, 1, 1, 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 'female')
(301, 1, 3, 'Kelly, Miss. Anna Katherine "Annie Kate"', 'female')
(302, 1, 3, 'McCoy, Mr. Bernard', 'male')
(303, 0, 3, 'Johnson, Mr. William Cahoone Jr', 'male')
(304, 1, 2, 'Keane, Miss. Nora A', 'female')
(305, 0, 3, 'Williams, Mr. Howard Hugh "Harry"', 'male')
(306, 1, 1, 'Allison, Master. Hudson Trevor', 'male')
(307, 1, 1, 'Fleming, Miss. Margaret', 'female')
(308, 1, 1, 'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)', 'female')
(309, 0, 2, 'Abelson, Mr. Samuel', 'male')
(310, 1, 1, 'Francatelli, Miss. Laura Mabel', 'female')
(311, 1, 1, 'Hays, Miss. Margaret Bechstein', 'female')
(312, 1, 1, 'Ryerson, Miss. Emily Borie', 'female')
(313, 0, 2, 'Lahtinen, Mrs. William (Anna Sylfven)', 'female')
(314, 0, 3, 'Hendekovic, Mr. Ignjac', 'male')
(315, 0, 2, 'Hart, Mr. Benjamin', 'male')
(316, 1, 3, 'Nilsson, Miss. Helmina Josefina', 'female')
(317, 1, 2, 'Kantor, Mrs. Sinai (Miriam Sternin)', 'female')
(318, 0, 2, 'Moraweck, Dr. Ernest', 'male')
(319, 1, 1, 'Wick, Miss. Mary Natalie', 'female')
(320, 1, 1, 'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)', 'female')
(321, 0, 3, 'Dennis, Mr. Samuel', 'male')
(322, 0, 3, 'Danoff, Mr. Yoto', 'male')
(323, 1, 2, 'Slayter, Miss. Hilda Mary', 'female')
(324, 1, 2, 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)', 'female')
(325, 0, 3, 'Sage, Mr. George John Jr', 'male')
(326, 1, 1, 'Young, Miss. Marie Grice', 'female')
(327, 0, 3, 'Nysveen, Mr. Johan Hansen', 'male')
(328, 1, 2, 'Ball, Mrs. (Ada E Hall)', 'female')
(329, 1, 3, 'Goldsmith, Mrs. Frank John (Emily Alice Brown)', 'female')
(330, 1, 1, 'Hippach, Miss. Jean Gertrude', 'female')
(331, 1, 3, 'McCoy, Miss. Agnes', 'female')
(332, 0, 1, 'Partner, Mr. Austen', 'male')
(333, 0, 1, 'Graham, Mr. George Edward', 'male')
(334, 0, 3, 'Vander Planke, Mr. Leo Edmondus', 'male')
(335, 1, 1, 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)', 'female')
(336, 0, 3, 'Denkoff, Mr. Mitto', 'male')
(337, 0, 1, 'Pears, Mr. Thomas Clinton', 'male')
(338, 1, 1, 'Burns, Miss. Elizabeth Margaret', 'female')
(339, 1, 3, 'Dahl, Mr. Karl Edwart', 'male')
(340, 0, 1, 'Blackwell, Mr. Stephen Weart', 'male')
(341, 1, 2, 'Navratil, Master. Edmond Roger', 'male')
(342, 1, 1, 'Fortune, Miss. Alice Elizabeth', 'female')
(343, 0, 2, 'Collander, Mr. Erik Gustaf', 'male')
(344, 0, 2, 'Sedgwick, Mr. Charles Frederick Waddington', 'male')
(345, 0, 2, 'Fox, Mr. Stanley Hubert', 'male')
(346, 1, 2, 'Brown, Miss. Amelia "Mildred"', 'female')
(347, 1, 2, 'Smith, Miss. Marion Elsie', 'female')
(348, 1, 3, 'Davison, Mrs. Thomas Henry (Mary E Finck)', 'female')
(349, 1, 3, 'Coutts, Master. William Loch "William"', 'male')
(350, 0, 3, 'Dimic, Mr. Jovan', 'male')
(351, 0, 3, 'Odahl, Mr. Nils Martin', 'male')
(352, 0, 1, 'Williams-Lambert, Mr. Fletcher Fellows', 'male')
(353, 0, 3, 'Elias, Mr. Tannous', 'male')
(354, 0, 3, 'Arnold-Franchi, Mr. Josef', 'male')
(355, 0, 3, 'Yousif, Mr. Wazli', 'male')
(356, 0, 3, 'Vanden Steen, Mr. Leo Peter', 'male')
(357, 1, 1, 'Bowerman, Miss. Elsie Edith', 'female')
(358, 0, 2, 'Funk, Miss. Annie Clemmer', 'female')
(359, 1, 3, 'McGovern, Miss. Mary', 'female')
(360, 1, 3, 'Mockler, Miss. Helen Mary "Ellie"', 'female')
(361, 0, 3, 'Skoog, Mr. Wilhelm', 'male')
(362, 0, 2, 'del Carlo, Mr. Sebastiano', 'male')
(363, 0, 3, 'Barbara, Mrs. (Catherine David)', 'female')
(364, 0, 3, 'Asim, Mr. Adola', 'male')
(365, 0, 3, "O'Brien, Mr. Thomas", 'male')
(366, 0, 3, 'Adahl, Mr. Mauritz Nils Martin', 'male')
(367, 1, 1, 'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)', 'female')
(368, 1, 3, 'Moussa, Mrs. (Mantoura Boulos)', 'female')
(369, 1, 3, 'Jermyn, Miss. Annie', 'female')
(370, 1, 1, 'Aubart, Mme. Leontine Pauline', 'female')
(371, 1, 1, 'Harder, Mr. George Achilles', 'male')
(372, 0, 3, 'Wiklund, Mr. Jakob Alfred', 'male')
(373, 0, 3, 'Beavan, Mr. William Thomas', 'male')
(374, 0, 1, 'Ringhini, Mr. Sante', 'male')
(375, 0, 3, 'Palsson, Miss. Stina Viola', 'female')
(376, 1, 1, 'Meyer, Mrs. Edgar Joseph (Leila Saks)', 'female')
(377, 1, 3, 'Landergren, Miss. Aurora Adelia', 'female')
(378, 0, 1, 'Widener, Mr. Harry Elkins', 'male')
(379, 0, 3, 'Betros, Mr. Tannous', 'male')
(380, 0, 3, 'Gustafsson, Mr. Karl Gideon', 'male')
(381, 1, 1, 'Bidois, Miss. Rosalie', 'female')
(382, 1, 3, 'Nakid, Miss. Maria ("Mary")', 'female')
(383, 0, 3, 'Tikkanen, Mr. Juho', 'male')
(384, 1, 1, 'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)', 'female')
(385, 0, 3, 'Plotcharsky, Mr. Vasil', 'male')
(386, 0, 2, 'Davies, Mr. Charles Henry', 'male')
(387, 0, 3, 'Goodwin, Master. Sidney Leonard', 'male')
(388, 1, 2, 'Buss, Miss. Kate', 'female')

In [65]:
cursor1.execute('''SELECT * 
                 FROM Titanic_02
                 
                 ''')
result3=cursor1.fetchall()   #fetch all the tuple

for i in result3:
    print(i)

(1, 1, 0, 'A/5 21171')
(2, 1, 0, 'PC 17599')
(3, 0, 0, 'STON/O2. 3101282')
(4, 1, 0, '113803')
(5, 0, 0, '373450')
(6, 0, 0, '330877')
(7, 0, 0, '17463')
(8, 3, 1, '349909')
(9, 0, 2, '347742')
(10, 1, 0, '237736')
(11, 1, 1, 'PP 9549')
(12, 0, 0, '113783')
(13, 0, 0, 'A/5. 2151')
(14, 1, 5, '347082')
(15, 0, 0, '350406')
(16, 0, 0, '248706')
(17, 4, 1, '382652')
(18, 0, 0, '244373')
(19, 1, 0, '345763')
(20, 0, 0, '2649')
(21, 0, 0, '239865')
(22, 0, 0, '248698')
(23, 0, 0, '330923')
(24, 0, 0, '113788')
(25, 3, 1, '349909')
(26, 1, 5, '347077')
(27, 0, 0, '2631')
(28, 3, 2, '19950')
(29, 0, 0, '330959')
(30, 0, 0, '349216')
(31, 0, 0, 'PC 17601')
(32, 1, 0, 'PC 17569')
(33, 0, 0, '335677')
(34, 0, 0, 'C.A. 24579')
(35, 1, 0, 'PC 17604')
(36, 1, 0, '113789')
(37, 0, 0, '2677')
(38, 0, 0, 'A./5. 2152')
(39, 2, 0, '345764')
(40, 1, 0, '2651')
(41, 1, 0, '7546')
(42, 1, 0, '11668')
(43, 0, 0, '349253')
(44, 1, 2, 'SC/Paris 2123')
(45, 0, 0, '330958')
(46, 0, 0, 'S.C./A.4. 23567')
(47, 1, 0, '370371')
(48, 0, 0, '14311')
(49, 2, 0, '2662')
(50, 1, 0, '349237')
(51, 4, 1, '3101295')
(52, 0, 0, 'A/4. 39886')
(53, 1, 0, 'PC 17572')
(54, 1, 0, '2926')
(55, 0, 1, '113509')
(56, 0, 0, '19947')
(57, 0, 0, 'C.A. 31026')
(58, 0, 0, '2697')
(59, 1, 2, 'C.A. 34651')
(60, 5, 2, 'CA 2144')
(61, 0, 0, '2669')
(62, 0, 0, '113572')
(63, 1, 0, '36973')
(64, 3, 2, '347088')
(65, 0, 0, 'PC 17605')
(66, 1, 1, '2661')
(67, 0, 0, 'C.A. 29395')
(68, 0, 0, 'S.P. 3464')
(69, 4, 2, '3101281')
(70, 2, 0, '315151')
(71, 0, 0, 'C.A. 33111')
(72, 5, 2, 'CA 2144')
(73, 0, 0, 'S.O.C. 14879')
(74, 1, 0, '2680')
(75, 0, 0, '1601')
(76, 0, 0, '348123')
(77, 0, 0, '349208')
(78, 0, 0, '374746')
(79, 0, 2, '248738')
(80, 0, 0, '364516')
(81, 0, 0, '345767')
(82, 0, 0, '345779')
(83, 0, 0, '330932')
(84, 0, 0, '113059')
(85, 0, 0, 'SO/C 14885')
(86, 3, 0, '3101278')
(87, 1, 3, 'W./C. 6608')
(88, 0, 0, 'SOTON/OQ 392086')
(89, 3, 2, '19950')
(90, 0, 0, '343275')
(91, 0, 0, '343276')
(92, 0, 0, '347466')
(93, 1, 0, 'W.E.P. 5734')
(94, 1, 2, 'C.A. 2315')
(95, 0, 0, '364500')
(96, 0, 0, '374910')
(97, 0, 0, 'PC 17754')
(98, 0, 1, 'PC 17759')
(99, 0, 1, '231919')
(100, 1, 0, '244367')
(101, 0, 0, '349245')
(102, 0, 0, '349215')
(103, 0, 1, '35281')
(104, 0, 0, '7540')
(105, 2, 0, '3101276')
(106, 0, 0, '349207')
(107, 0, 0, '343120')
(108, 0, 0, '312991')
(109, 0, 0, '349249')
(110, 1, 0, '371110')
(111, 0, 0, '110465')
(112, 1, 0, '2665')
(113, 0, 0, '324669')
(114, 1, 0, '4136')
(115, 0, 0, '2627')
(116, 0, 0, 'STON/O 2. 3101294')
(117, 0, 0, '370369')
(118, 1, 0, '11668')
(119, 0, 1, 'PC 17558')
(120, 4, 2, '347082')
(121, 2, 0, 'S.O.C. 14879')
(122, 0, 0, 'A4. 54510')
(123, 1, 0, '237736')
(124, 0, 0, '27267')
(125, 0, 1, '35281')
(126, 1, 0, '2651')
(127, 0, 0, '370372')
(128, 0, 0, 'C 17369')
(129, 1, 1, '2668')
(130, 0, 0, '347061')
(131, 0, 0, '349241')
(132, 0, 0, 'SOTON/O.Q. 3101307')
(133, 1, 0, 'A/5. 3337')
(134, 1, 0, '228414')
(135, 0, 0, 'C.A. 29178')
(136, 0, 0, 'SC/PARIS 2133')
(137, 0, 2, '11752')
(138, 1, 0, '113803')
(139, 0, 0, '7534')
(140, 0, 0, 'PC 17593')
(141, 0, 2, '2678')
(142, 0, 0, '347081')
(143, 1, 0, 'STON/O2. 3101279')
(144, 0, 0, '365222')
(145, 0, 0, '231945')
(146, 1, 1, 'C.A. 33112')
(147, 0, 0, '350043')
(148, 2, 2, 'W./C. 6608')
(149, 0, 2, '230080')
(150, 0, 0, '244310')
(151, 0, 0, 'S.O.P. 1166')
(152, 1, 0, '113776')
(153, 0, 0, 'A.5. 11206')
(154, 0, 2, 'A/5. 851')
(155, 0, 0, 'Fa 265302')
(156, 0, 1, 'PC 17597')
(157, 0, 0, '35851')
(158, 0, 0, 'SOTON/OQ 392090')
(159, 0, 0, '315037')
(160, 8, 2, 'CA. 2343')
(161, 0, 1, '371362')
(162, 0, 0, 'C.A. 33595')
(163, 0, 0, '347068')
(164, 0, 0, '315093')
(165, 4, 1, '3101295')
(166, 0, 2, '363291')
(167, 0, 1, '113505')
(168, 1, 4, '347088')
(169, 0, 0, 'PC 17318')
(170, 0, 0, '1601')
(171, 0, 0, '111240')
(172, 4, 1, '382652')
(173, 1, 1, '347742')
(174, 0, 0, 'STON/O 2. 3101280')
(175, 0, 0, '17764')
(176, 1, 1, '350404')
(177, 3, 1, '4133')
(178, 0, 0, 'PC 17595')
(179, 0, 0, '250653')
(180, 0, 0, 'LINE')
(181, 8, 2, 'CA. 2343')
(182, 0, 0, 'SC/PARIS 2131')
(183, 4, 2, '347077')
(184, 2, 1, '230136')
(185, 0, 2, '315153')
(186, 0, 0, '113767')
(187, 1, 0, '370365')
(188, 0, 0, '111428')
(189, 1, 1, '364849')
(190, 0, 0, '349247')
(191, 0, 0, '234604')
(192, 0, 0, '28424')
(193, 1, 0, '350046')
(194, 1, 1, '230080')
(195, 0, 0, 'PC 17610')
(196, 0, 0, 'PC 17569')
(197, 0, 0, '368703')
(198, 0, 1, '4579')
(199, 0, 0, '370370')
(200, 0, 0, '248747')
(201, 0, 0, '345770')
(202, 8, 2, 'CA. 2343')
(203, 0, 0, '3101264')
(204, 0, 0, '2628')
(205, 0, 0, 'A/5 3540')
(206, 0, 1, '347054')
(207, 1, 0, '3101278')
(208, 0, 0, '2699')
(209, 0, 0, '367231')
(210, 0, 0, '112277')
(211, 0, 0, 'SOTON/O.Q. 3101311')
(212, 0, 0, 'F.C.C. 13528')
(213, 0, 0, 'A/5 21174')
(214, 0, 0, '250646')
(215, 1, 0, '367229')
(216, 1, 0, '35273')
(217, 0, 0, 'STON/O2. 3101283')
(218, 1, 0, '243847')
(219, 0, 0, '11813')
(220, 0, 0, 'W/C 14208')
(221, 0, 0, 'SOTON/OQ 392089')
(222, 0, 0, '220367')
(223, 0, 0, '21440')
(224, 0, 0, '349234')
(225, 1, 0, '19943')
(226, 0, 0, 'PP 4348')
(227, 0, 0, 'SW/PP 751')
(228, 0, 0, 'A/5 21173')
(229, 0, 0, '236171')
(230, 3, 1, '4133')
(231, 1, 0, '36973')
(232, 0, 0, '347067')
(233, 0, 0, '237442')
(234, 4, 2, '347077')
(235, 0, 0, 'C.A. 29566')
(236, 0, 0, 'W./C. 6609')
(237, 1, 0, '26707')
(238, 0, 2, 'C.A. 31921')
(239, 0, 0, '28665')
(240, 0, 0, 'SCO/W 1585')
(241, 1, 0, '2665')
(242, 1, 0, '367230')
(243, 0, 0, 'W./C. 14263')
(244, 0, 0, 'STON/O 2. 3101275')
(245, 0, 0, '2694')
(246, 2, 0, '19928')
(247, 0, 0, '347071')
(248, 0, 2, '250649')
(249, 1, 1, '11751')
(250, 1, 0, '244252')
(251, 0, 0, '362316')
(252, 1, 1, '347054')
(253, 0, 0, '113514')
(254, 1, 0, 'A/5. 3336')
(255, 0, 2, '370129')
(256, 0, 2, '2650')
(257, 0, 0, 'PC 17585')
(258, 0, 0, '110152')
(259, 0, 0, 'PC 17755')
(260, 0, 1, '230433')
(261, 0, 0, '384461')
(262, 4, 2, '347077')
(263, 1, 1, '110413')
(264, 0, 0, '112059')
(265, 0, 0, '382649')
(266, 0, 0, 'C.A. 17248')
(267, 4, 1, '3101295')
(268, 1, 0, '347083')
(269, 0, 1, 'PC 17582')
(270, 0, 0, 'PC 17760')
(271, 0, 0, '113798')
(272, 0, 0, 'LINE')
(273, 0, 1, '250644')
(274, 0, 1, 'PC 17596')
(275, 0, 0, '370375')
(276, 1, 0, '13502')
(277, 0, 0, '347073')
(278, 0, 0, '239853')
(279, 4, 1, '382652')
(280, 1, 1, 'C.A. 2673')
(281, 0, 0, '336439')
(282, 0, 0, '347464')
(283, 0, 0, '345778')
(284, 0, 0, 'A/5. 10482')
(285, 0, 0, '113056')
(286, 0, 0, '349239')
(287, 0, 0, '345774')
(288, 0, 0, '349206')
(289, 0, 0, '237798')
(290, 0, 0, '370373')
(291, 0, 0, '19877')
(292, 1, 0, '11967')
(293, 0, 0, 'SC/Paris 2163')
(294, 0, 0, '349236')
(295, 0, 0, '349233')
(296, 0, 0, 'PC 17612')
(297, 0, 0, '2693')
(298, 1, 2, '113781')
(299, 0, 0, '19988')
(300, 0, 1, 'PC 17558')
(301, 0, 0, '9234')
(302, 2, 0, '367226')
(303, 0, 0, 'LINE')
(304, 0, 0, '226593')
(305, 0, 0, 'A/5 2466')
(306, 1, 2, '113781')
(307, 0, 0, '17421')
(308, 1, 0, 'PC 17758')
(309, 1, 0, 'P/PP 3381')
(310, 0, 0, 'PC 17485')
(311, 0, 0, '11767')
(312, 2, 2, 'PC 17608')
(313, 1, 1, '250651')
(314, 0, 0, '349243')
(315, 1, 1, 'F.C.C. 13529')
(316, 0, 0, '347470')
(317, 1, 0, '244367')
(318, 0, 0, '29011')
(319, 0, 2, '36928')
(320, 1, 1, '16966')
(321, 0, 0, 'A/5 21172')
(322, 0, 0, '349219')
(323, 0, 0, '234818')
(324, 1, 1, '248738')
(325, 8, 2, 'CA. 2343')
(326, 0, 0, 'PC 17760')
(327, 0, 0, '345364')
(328, 0, 0, '28551')
(329, 1, 1, '363291')
(330, 0, 1, '111361')
(331, 2, 0, '367226')
(332, 0, 0, '113043')
(333, 0, 1, 'PC 17582')
(334, 2, 0, '345764')
(335, 1, 0, 'PC 17611')
(336, 0, 0, '349225')
(337, 1, 0, '113776')
(338, 0, 0, '16966')
(339, 0, 0, '7598')
(340, 0, 0, '113784')
(341, 1, 1, '230080')
(342, 3, 2, '19950')
(343, 0, 0, '248740')
(344, 0, 0, '244361')
(345, 0, 0, '229236')
(346, 0, 0, '248733')
(347, 0, 0, '31418')
(348, 1, 0, '386525')
(349, 1, 1, 'C.A. 37671')
(350, 0, 0, '315088')
(351, 0, 0, '7267')
(352, 0, 0, '113510')
(353, 1, 1, '2695')
(354, 1, 0, '349237')
(355, 0, 0, '2647')
(356, 0, 0, '345783')
(357, 0, 1, '113505')
(358, 0, 0, '237671')
(359, 0, 0, '330931')
(360, 0, 0, '330980')
(361, 1, 4, '347088')
(362, 1, 0, 'SC/PARIS 2167')
(363, 0, 1, '2691')
(364, 0, 0, 'SOTON/O.Q. 3101310')
(365, 1, 0, '370365')
(366, 0, 0, 'C 7076')
(367, 1, 0, '110813')
(368, 0, 0, '2626')
(369, 0, 0, '14313')
(370, 0, 0, 'PC 17477')
(371, 1, 0, '11765')
(372, 1, 0, '3101267')
(373, 0, 0, '323951')
(374, 0, 0, 'PC 17760')
(375, 3, 1, '349909')
(376, 1, 0, 'PC 17604')
(377, 0, 0, 'C 7077')
(378, 0, 2, '113503')
(379, 0, 0, '2648')
(380, 0, 0, '347069')
(381, 0, 0, 'PC 17757')
(382, 0, 2, '2653')
(383, 0, 0, 'STON/O 2. 3101293')
(384, 1, 0, '113789')
(385, 0, 0, '349227')
(386, 0, 0, 'S.O.C. 14879')
(387, 5, 2, 'CA 2144')
(388, 0, 0, '27849')
(389, 0, 0, '367655')
(390, 0, 0, 'SC 1748')
(391, 1, 2, '113760')
(392, 0, 0, '350034')
(393, 2, 0, '3101277')
(394, 1, 0, '35273')
(395, 0, 2, 'PP 9549')
(396, 0, 0, '350052')
(397, 0, 0, '350407')
(398, 0, 0, '28403')
(399, 0, 0, '244278')
(400, 0, 0, '240929')
(401, 0, 0, 'STON/O 2. 3101289')
(402, 0, 0, '341826')
(403, 1, 0, '4137')
(404, 1, 0, 'STON/O2. 3101279')
(405, 0, 0, '315096')
(406, 1, 0, '28664')
(407, 0, 0, '347064')
(408, 1, 1, '29106')
(409, 0, 0, '312992')
(410, 3, 1, '4133')
(411, 0, 0, '349222')
(412, 0, 0, '394140')
(413, 1, 0, '19928')
(414, 0, 0, '239853')
(415, 0, 0, 'STON/O 2. 3101269')
(416, 0, 0, '343095')
(417, 1, 1, '28220')
(418, 0, 2, '250652')
(419, 0, 0, '28228')
(420, 0, 2, '345773')
(421, 0, 0, '349254')
(422, 0, 0, 'A/5. 13032')
(423, 0, 0, '315082')
(424, 1, 1, '347080')
(425, 1, 1, '370129')
(426, 0, 0, 'A/4. 34244')
(427, 1, 0, '2003')
(428, 0, 0, '250655')
(429, 0, 0, '364851')
(430, 0, 0, 'SOTON/O.Q. 392078')
(431, 0, 0, '110564')
(432, 1, 0, '376564')
(433, 1, 0, 'SC/AH 3085')
(434, 0, 0, 'STON/O 2. 3101274')
(435, 1, 0, '13507')
(436, 1, 2, '113760')
(437, 2, 2, 'W./C. 6608')
(438, 2, 3, '29106')
(439, 1, 4, '19950')
(440, 0, 0, 'C.A. 18723')
(441, 1, 1, 'F.C.C. 13529')
(442, 0, 0, '345769')
(443, 1, 0, '347076')
(444, 0, 0, '230434')
(445, 0, 0, '65306')
(446, 0, 2, '33638')
(447, 0, 1, '250644')
(448, 0, 0, '113794')
(449, 2, 1, '2666')
(450, 0, 0, '113786')
(451, 1, 2, 'C.A. 34651')
(452, 1, 0, '65303')
(453, 0, 0, '113051')
(454, 1, 0, '17453')
(455, 0, 0, 'A/5 2817')
(456, 0, 0, '349240')
(457, 0, 0, '13509')
(458, 1, 0, '17464')
(459, 0, 0, 'F.C.C. 13531')
(460, 0, 0, '371060')
(461, 0, 0, '19952')
(462, 0, 0, '364506')
(463, 0, 0, '111320')
(464, 0, 0, '234360')
(465, 0, 0, 'A/S 2816')
(466, 0, 0, 'SOTON/O.Q. 3101306')
(467, 0, 0, '239853')
(468, 0, 0, '113792')
(469, 0, 0, '36209')
(470, 2, 1, '2666')
(471, 0, 0, '323592')
(472, 0, 0, '315089')
(473, 1, 2, 'C.A. 34651')
(474, 0, 0, 'SC/AH Basle 541')
(475, 0, 0, '7553')
(476, 0, 0, '110465')
(477, 1, 0, '31027')
(478, 1, 0, '3460')
(479, 0, 0, '350060')
(480, 0, 1, '3101298')
(481, 5, 2, 'CA 2144')
(482, 0, 0, '239854')
(483, 0, 0, 'A/5 3594')
(484, 0, 0, '4134')
(485, 1, 0, '11967')
(486, 3, 1, '4133')
(487, 1, 0, '19943')
(488, 0, 0, '11771')
(489, 0, 0, 'A.5. 18509')
(490, 1, 1, 'C.A. 37671')
(491, 1, 0, '65304')
(492, 0, 0, 'SOTON/OQ 3101317')
(493, 0, 0, '113787')
(494, 0, 0, 'PC 17609')
(495, 0, 0, 'A/4 45380')
(496, 0, 0, '2627')
(497, 1, 0, '36947')
(498, 0, 0, 'C.A. 6212')
(499, 1, 2, '113781')
(500, 0, 0, '350035')
(501, 0, 0, '315086')
(502, 0, 0, '364846')
(503, 0, 0, '330909')
(504, 0, 0, '4135')
(505, 0, 0, '110152')
(506, 1, 0, 'PC 17758')
(507, 0, 2, '26360')
(508, 0, 0, '111427')
(509, 0, 0, 'C 4001')
(510, 0, 0, '1601')
(511, 0, 0, '382651')
(512, 0, 0, 'SOTON/OQ 3101316')
(513, 0, 0, 'PC 17473')
(514, 1, 0, 'PC 17603')
(515, 0, 0, '349209')
(516, 0, 0, '36967')
(517, 0, 0, 'C.A. 34260')
(518, 0, 0, '371110')
(519, 1, 0, '226875')
(520, 0, 0, '349242')
(521, 0, 0, '12749')
(522, 0, 0, '349252')
(523, 0, 0, '2624')
(524, 0, 1, '111361')
(525, 0, 0, '2700')
(526, 0, 0, '367232')
(527, 0, 0, 'W./C. 14258')
(528, 0, 0, 'PC 17483')
(529, 0, 0, '3101296')
(530, 2, 1, '29104')
(531, 1, 1, '26360')
(532, 0, 0, '2641')
(533, 1, 1, '2690')
(534, 0, 2, '2668')
(535, 0, 0, '315084')
(536, 0, 2, 'F.C.C. 13529')
(537, 0, 0, '113050')
(538, 0, 0, 'PC 17761')
(539, 0, 0, '364498')
(540, 0, 2, '13568')
(541, 0, 2, 'WE/P 5735')
(542, 4, 2, '347082')
(543, 4, 2, '347082')
(544, 1, 0, '2908')
(545, 1, 0, 'PC 17761')
(546, 0, 0, '693')
(547, 1, 0, '2908')
(548, 0, 0, 'SC/PARIS 2146')
(549, 1, 1, '363291')
(550, 1, 1, 'C.A. 33112')
(551, 0, 2, '17421')
(552, 0, 0, '244358')
(553, 0, 0, '330979')
(554, 0, 0, '2620')
(555, 0, 0, '347085')
(556, 0, 0, '113807')
(557, 1, 0, '11755')
(558, 0, 0, 'PC 17757')
(559, 1, 1, '110413')
(560, 1, 0, '345572')
(561, 0, 0, '372622')
(562, 0, 0, '349251')
(563, 0, 0, '218629')
(564, 0, 0, 'SOTON/OQ 392082')
(565, 0, 0, 'SOTON/O.Q. 392087')
(566, 2, 0, 'A/4 48871')
(567, 0, 0, '349205')
(568, 0, 4, '349909')
(569, 0, 0, '2686')
(570, 0, 0, '350417')
(571, 0, 0, 'S.W./PP 752')
(572, 2, 0, '11769')
(573, 0, 0, 'PC 17474')
(574, 0, 0, '14312')
(575, 0, 0, 'A/4. 20589')
(576, 0, 0, '358585')
(577, 0, 0, '243880')
(578, 1, 0, '13507')
(579, 1, 0, '2689')
(580, 0, 0, 'STON/O 2. 3101286')
(581, 1, 1, '237789')
(582, 1, 1, '17421')
(583, 0, 0, '28403')
(584, 0, 0, '13049')
(585, 0, 0, '3411')
(586, 0, 2, '110413')
(587, 0, 0, '237565')
(588, 1, 1, '13567')
(589, 0, 0, '14973')
(590, 0, 0, 'A./5. 3235')
(591, 0, 0, 'STON/O 2. 3101273')
(592, 1, 0, '36947')
(593, 0, 0, 'A/5 3902')
(594, 0, 2, '364848')
(595, 1, 0, 'SC/AH 29037')
(596, 1, 1, '345773')
(597, 0, 0, '248727')
(598, 0, 0, 'LINE')
(599, 0, 0, '2664')
(600, 1, 0, 'PC 17485')
(601, 2, 1, '243847')
(602, 0, 0, '349214')
(603, 0, 0, '113796')
(604, 0, 0, '364511')
(605, 0, 0, '111426')
(606, 1, 0, '349910')
(607, 0, 0, '349246')
(608, 0, 0, '113804')
(609, 1, 2, 'SC/Paris 2123')
(610, 0, 0, 'PC 17582')
(611, 1, 5, '347082')
(612, 0, 0, 'SOTON/O.Q. 3101305')
(613, 1, 0, '367230')
(614, 0, 0, '370377')
(615, 0, 0, '364512')
(616, 1, 2, '220845')
(617, 1, 1, '347080')
(618, 1, 0, 'A/5. 3336')
(619, 2, 1, '230136')
(620, 0, 0, '31028')
(621, 1, 0, '2659')
(622, 1, 0, '11753')
(623, 1, 1, '2653')
(624, 0, 0, '350029')
(625, 0, 0, '54636')
(626, 0, 0, '36963')
(627, 0, 0, '219533')
(628, 0, 0, '13502')
(629, 0, 0, '349224')
(630, 0, 0, '334912')
(631, 0, 0, '27042')
(632, 0, 0, '347743')
(633, 0, 0, '13214')
(634, 0, 0, '112052')
(635, 3, 2, '347088')
(636, 0, 0, '237668')
(637, 0, 0, 'STON/O 2. 3101292')
(638, 1, 1, 'C.A. 31921')
(639, 0, 5, '3101295')
(640, 1, 0, '376564')
(641, 0, 0, '350050')
(642, 0, 0, 'PC 17477')
(643, 3, 2, '347088')
(644, 0, 0, '1601')
(645, 2, 1, '2666')
(646, 1, 0, 'PC 17572')
(647, 0, 0, '349231')
(648, 0, 0, '13213')
(649, 0, 0, 'S.O./P.P. 751')
(650, 0, 0, 'CA. 2314')
(651, 0, 0, '349221')
(652, 0, 1, '231919')
(653, 0, 0, '8475')
(654, 0, 0, '330919')
(655, 0, 0, '365226')
(656, 2, 0, 'S.O.C. 14879')
(657, 0, 0, '349223')
(658, 1, 1, '364849')
(659, 0, 0, '29751')
(660, 0, 2, '35273')
(661, 2, 0, 'PC 17611')
(662, 0, 0, '2623')
(663, 0, 0, '5727')
(664, 0, 0, '349210')
(665, 1, 0, 'STON/O 2. 3101285')
(666, 2, 0, 'S.O.C. 14879')
(667, 0, 0, '234686')
(668, 0, 0, '312993')
(669, 0, 0, 'A/5 3536')
(670, 1, 0, '19996')
(671, 1, 1, '29750')
(672, 1, 0, 'F.C. 12750')
(673, 0, 0, 'C.A. 24580')
(674, 0, 0, '244270')
(675, 0, 0, '239856')
(676, 0, 0, '349912')
(677, 0, 0, '342826')
(678, 0, 0, '4138')
(679, 1, 6, 'CA 2144')
(680, 0, 1, 'PC 17755')
(681, 0, 0, '330935')
(682, 0, 0, 'PC 17572')
(683, 0, 0, '6563')
(684, 5, 2, 'CA 2144')
(685, 1, 1, '29750')
(686, 1, 2, 'SC/Paris 2123')
(687, 4, 1, '3101295')
(688, 0, 0, '349228')
(689, 0, 0, '350036')
(690, 0, 1, '24160')
(691, 1, 0, '17474')
(692, 0, 1, '349256')
(693, 0, 0, '1601')
(694, 0, 0, '2672')
(695, 0, 0, '113800')
(696, 0, 0, '248731')
(697, 0, 0, '363592')
(698, 0, 0, '35852')
(699, 1, 1, '17421')
(700, 0, 0, '348121')
(701, 1, 0, 'PC 17757')
(702, 0, 0, 'PC 17475')
(703, 0, 1, '2691')
(704, 0, 0, '36864')
(705, 1, 0, '350025')
(706, 0, 0, '250655')
(707, 0, 0, '223596')
(708, 0, 0, 'PC 17476')
(709, 0, 0, '113781')
(710, 1, 1, '2661')
(711, 0, 0, 'PC 17482')
(712, 0, 0, '113028')
(713, 1, 0, '19996')
(714, 0, 0, '7545')
(715, 0, 0, '250647')
(716, 0, 0, '348124')
(717, 0, 0, 'PC 17757')
(718, 0, 0, '34218')
(719, 0, 0, '36568')
(720, 0, 0, '347062')
(721, 0, 1, '248727')
(722, 1, 0, '350048')
(723, 0, 0, '12233')
(724, 0, 0, '250643')
(725, 1, 0, '113806')
(726, 0, 0, '315094')
(727, 3, 0, '31027')
(728, 0, 0, '36866')
(729, 1, 0, '236853')
(730, 1, 0, 'STON/O2. 3101271')
(731, 0, 0, '24160')
(732, 0, 0, '2699')
(733, 0, 0, '239855')
(734, 0, 0, '28425')
(735, 0, 0, '233639')
(736, 0, 0, '54636')
(737, 1, 3, 'W./C. 6608')
(738, 0, 0, 'PC 17755')
(739, 0, 0, '349201')
(740, 0, 0, '349218')
(741, 0, 0, '16988')
(742, 1, 0, '19877')
(743, 2, 2, 'PC 17608')
(744, 1, 0, '376566')
(745, 0, 0, 'STON/O 2. 3101288')
(746, 1, 1, 'WE/P 5735')
(747, 1, 1, 'C.A. 2673')
(748, 0, 0, '250648')
(749, 1, 0, '113773')
(750, 0, 0, '335097')
(751, 1, 1, '29103')
(752, 0, 1, '392096')
(753, 0, 0, '345780')
(754, 0, 0, '349204')
(755, 1, 2, '220845')
(756, 1, 1, '250649')
(757, 0, 0, '350042')
(758, 0, 0, '29108')
(759, 0, 0, '363294')
(760, 0, 0, '110152')
(761, 0, 0, '358585')
(762, 0, 0, 'SOTON/O2 3101272')
(763, 0, 0, '2663')
(764, 1, 2, '113760')
(765, 0, 0, '347074')
(766, 1, 0, '13502')
(767, 0, 0, '112379')
(768, 0, 0, '364850')
(769, 1, 0, '371110')
(770, 0, 0, '8471')
(771, 0, 0, '345781')
(772, 0, 0, '350047')
(773, 0, 0, 'S.O./P.P. 3')
(774, 0, 0, '2674')
(775, 1, 3, '29105')
(776, 0, 0, '347078')
(777, 0, 0, '383121')
(778, 0, 0, '364516')
(779, 0, 0, '36865')
(780, 0, 1, '24160')
(781, 0, 0, '2687')
(782, 1, 0, '17474')
(783, 0, 0, '113501')
(784, 1, 2, 'W./C. 6607')
(785, 0, 0, 'SOTON/O.Q. 3101312')
(786, 0, 0, '374887')
(787, 0, 0, '3101265')
(788, 4, 1, '382652')
(789, 1, 2, 'C.A. 2315')
(790, 0, 0, 'PC 17593')
(791, 0, 0, '12460')
(792, 0, 0, '239865')
(793, 8, 2, 'CA. 2343')
(794, 0, 0, 'PC 17600')
(795, 0, 0, '349203')
(796, 0, 0, '28213')
(797, 0, 0, '17465')
(798, 0, 0, '349244')
(799, 0, 0, '2685')
(800, 1, 1, '345773')
(801, 0, 0, '250647')
(802, 1, 1, 'C.A. 31921')
(803, 1, 2, '113760')
(804, 0, 1, '2625')
(805, 0, 0, '347089')
(806, 0, 0, '347063')
(807, 0, 0, '112050')
(808, 0, 0, '347087')
(809, 0, 0, '248723')
(810, 1, 0, '113806')
(811, 0, 0, '3474')
(812, 0, 0, 'A/4 48871')
(813, 0, 0, '28206')
(814, 4, 2, '347082')
(815, 0, 0, '364499')
(816, 0, 0, '112058')
(817, 0, 0, 'STON/O2. 3101290')
(818, 1, 1, 'S.C./PARIS 2079')
(819, 0, 0, 'C 7075')
(820, 3, 2, '347088')
(821, 1, 1, '12749')
(822, 0, 0, '315098')
(823, 0, 0, '19972')
(824, 0, 1, '392096')
(825, 4, 1, '3101295')
(826, 0, 0, '368323')
(827, 0, 0, '1601')
(828, 0, 2, 'S.C./PARIS 2079')
(829, 0, 0, '367228')
(830, 0, 0, '113572')
(831, 1, 0, '2659')
(832, 1, 1, '29106')
(833, 0, 0, '2671')
(834, 0, 0, '347468')
(835, 0, 0, '2223')
(836, 1, 1, 'PC 17756')
(837, 0, 0, '315097')
(838, 0, 0, '392092')
(839, 0, 0, '1601')
(840, 0, 0, '11774')
(841, 0, 0, 'SOTON/O2 3101287')
(842, 0, 0, 'S.O./P.P. 3')
(843, 0, 0, '113798')
(844, 0, 0, '2683')
(845, 0, 0, '315090')
(846, 0, 0, 'C.A. 5547')
(847, 8, 2, 'CA. 2343')
(848, 0, 0, '349213')
(849, 0, 1, '248727')
(850, 1, 0, '17453')
(851, 4, 2, '347082')
(852, 0, 0, '347060')
(853, 1, 1, '2678')
(854, 0, 1, 'PC 17592')
(855, 1, 0, '244252')
(856, 0, 1, '392091')
(857, 1, 1, '36928')
(858, 0, 0, '113055')
(859, 0, 3, '2666')
(860, 0, 0, '2629')
(861, 2, 0, '350026')
(862, 1, 0, '28134')
(863, 0, 0, '17466')
(864, 8, 2, 'CA. 2343')
(865, 0, 0, '233866')
(866, 0, 0, '236852')
(867, 1, 0, 'SC/PARIS 2149')
(868, 0, 0, 'PC 17590')
(869, 0, 0, '345777')
(870, 1, 1, '347742')
(871, 0, 0, '349248')
(872, 1, 1, '11751')
(873, 0, 0, '695')
(874, 0, 0, '345765')
(875, 1, 0, 'P/PP 3381')
(876, 0, 0, '2667')
(877, 0, 0, '7534')
(878, 0, 0, '349212')
(879, 0, 0, '349217')
(880, 0, 1, '11767')
(881, 0, 1, '230433')
(882, 0, 0, '349257')
(883, 0, 0, '7552')
(884, 0, 0, 'C.A./SOTON 34068')